export const GOOGLEMAPS_API_KEY = 'AIzaSyA7xvPRNYootj8dExDMjhnLIcytrPWJsn4';
export const FOURSQUARE_CLIENT_ID = 'TVWIZPA02B2EPWGRLJ2BQAMKFOUDRDXO453XJT43D5RDI5PI';
export const FOURSQUARE_CLIENT_SECRET = '0BUV51W4I4FLRATEQKC5MBBOSZSS1YCSHAJKJTZT0RH4YUKT';